title: "Honeypot Anomaly Detection"
description: "Unsupervised Multi-Layer Anomaly Detection and Attack Chain Extraction"
baseurl: "/Thesis"
url: "https://johanneslks.github.io"
theme: minimal-mistakes-jekyll
markdown: kramdown
kramdown:
  math_engine: mathjax

# Enable top navigation bar:
header_pages:
  - index.md
  - documentation/index.md
