title: Honeypot Anomaly Detection
theme: just-the-docs

url: "https://johanneslks.github.io"
baseurl: "/Thesis"

# Enable callouts and math support
just_the_docs:
  collections:
    documentation:
      name: Documentation
      nav_exclude: false
  search_enabled: true
  math: true
