site_name: Honeypot Anomaly Detection
site_url: https://johanneslks.github.io/Thesis
theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - search.highlight
markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
      inline_syntax: ['dollar', 'round']
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home: index.md
  - Documentation:
      - Overview: documentation/index.md
      - Related Work: documentation/relatedWork.md
      - Journals: documentation/journals.md
      - Thoughts: documentation/thoughts.md
      - Mathematical Formulation: documentation/math.md