site_name: Honeypot Anomaly Detection
site_url: https://johanneslks.github.io/Thesis
theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - search.highlight

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.arithmatex:
      generic: true
      inline_syntax: ['dollar', 'round']
  - admonition
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tabbed

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Documentation:
      - Overview: documentation/index.md
      - Related Work: documentation/relatedWork.md
      - Journals: documentation/journals.md
      - Thoughts: documentation/thoughts.md
      - Mathematical Formulation: documentation/math.md
